name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: read
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Congratulations, ${{ github.actor }}! 🎉 Thank you for creating your first issue here. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work!"
          pr-message: "Great job, ${{ github.actor }}! 🎉 Thank you for submitting your first pull request here. Your contribution is valuable and we appreciate your efforts to improve our project. We'll review your changes and provide feedback as soon as possible. Keep up the great work!"
